### ISSUE TITLE
Missing CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/PathDSP#12]
https://github.com/JDACS4C-IMPROVE/PathDSP/blame/889253017cee4d6463803c66d455e587b948ba7c/train.sh#L18-L21

Why did you remove CUDA_VISIBLE_DEVICES from the train script? Please leave it in there even when your model is not using any GPU. This makes the train scripts consistent for all models.

**Comment by Liuy12** [comment]
fixed both train.sh and infer.sh scripts #15
