### ISSUE TITLE
Missing module: polars

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/PathDSP#3]
Command: `singularity exec --bind ${TEST_DIR}:/candle_data_dir build/PathDSP.sif /usr/local/PathDSP/train.sh 5 /candle_data_dir --epochs 1`

Output:

--epochs is not a file
CMD = python /usr/local/PathDSP/train.py --epochs 1
using data from /candle_data_dir
/candle_data_dir//Data
/usr/local/PathDSP/train.sh: line 72: ./candle_glue.sh: No such file or directory
using original data placed in /candle_data_dir//Data
using CUDA_VISIBLE_DEVICES 5
using CANDLE_DATA_DIR /candle_data_dir
using CANDLE_CONFIG
activating environment
Not a conda environment: /usr/local/conda_envs/PathDSP_env
running command python /usr/local/PathDSP/train.py --epochs 1
Importing candle utils for pytorch
Traceback (most recent call last):
  File "/usr/local/PathDSP/train.py", line 6, in <module>
    from preprocess_new import mkdir, preprocess
  File "/usr/local/PathDSP/preprocess_new.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'

**Comment by wilke** [comment]
Are there a requirements file or install instructions?

**Comment by Liuy12** [comment]
I have updated documentation
